#!/bin/bash
#
# Title:      PlexGuide (Reference Title File)
# Author(s):  Admin9705
# URL:        https://plexguide.com - http://github.plexguide.com
# GNU:        General Public License v3.0
################################################################################
---
- hosts: localhost
  gather_facts: false
  tasks:

    # WP CORE (MANDATORY) #########################################################
    - name: 'Including PG Press Core'
      include_tasks: '/opt/pgapache/pgapachecore.yml'

    # FACTS #######################################################################
    - name: 'Set Known Facts'
      set_fact:
        pgrole: 'ap-{{ap_id.stdout}}'
        intport: '80'
        extport: '80'
        image: 'geerlingguy/php-apache:latest'

    # CORE (MANDATORY) ############################################################
    - name: 'Register TLD'
      shell: 'cat /var/plexguide/tld.program'
      register: toplevel

    - name: Register Domain
      shell: 'cat /var/plexguide/server.domain'
      register: domain

    - name: 'If Fact Matches - Enable TLD'
      set_fact:
        tldset: '{{domain.stdout}}'
      when: 'toplevel.stdout == ap_id.stdout'

    - name: 'If Fact Does Not Match - Ignore TLD'
      set_fact:
        tldset: ''
      when: 'not toplevel.stdout == ap_id.stdout'

    # LABELS ######################################################################
    - name: 'Adding Traefik'
      set_fact:
        pg_labels:
          traefik.enable: 'true'
          traefik.backend: "{{pgrole}}"
          traefik.port: '80'
          traefik.frontend.rule: 'Host:{{ap_id.stdout}}.{{domain.stdout}},{{tldset}}'
          traefik.docker.network: 'plexguide'

    - name: 'Setting PG Volumes'
      set_fact:
        pg_volumes:
          - /opt/appdata/wordpress/{{ap_id.stdout}}/{{ap_id.stdout}}:/var/www/html
          - /etc/localtime:/etc/localtime:ro

    - name: 'Setting PG ENV'
      set_fact:
        pg_env:
          PUID: 1000
          PGID: 1000

    # MAIN DEPLOYMENT #############################################################
    - name: 'Deploying {{pgrole}}'
      docker_container:
        name: '{{pgrole}}'
        image: '{{image}}'
        pull: yes
        volumes: '{{pg_volumes}}'
        env: '{{pg_env}}'
        restart_policy: unless-stopped
        command: ["/usr/sbin/apache2ctl", "-D", "FOREGROUND"]
        networks:
          - name: plexguide
            aliases:
              - "ap-{{ap_id.stdout}}"
        state: started
        labels: '{{pg_labels}}'
